print("Enter 9 to the power 3 is :",9**3)
print("Enter 9 to the divide 3 is :",9//4)
print("Multiplication is :",3*4)
print("3 raise to 4 is :",3**4)
print("Division in floating point is :",3/4)
print("Division not in floating point is :",9//4)
print("Addition of 3 and 4 is :",3+4)
print("Subtraction of 3 and 4 is :",3-4)
print("Modulo of 3 and 4 is :",3%4)
